"""Generate supabase/seed.sql from the cleaned corpus CSVs.

Emits idempotent INSERTs for:
  * `coder`     — two placeholder coders (link auth_user_id after inviting users)
  * `programme` — all rows of data/cleaned/corpus_inventory.csv, with in_tier_b
                  flagged from data/cleaned/tier_b_sample_ids.csv

Reference data (MRCDD areas/competences) is NOT emitted here — it lives in the
canonical migration 20260709120300_reference_seed.sql.

Run from the project root:
    python scripts/python/db/generate_seed.py

Paths are resolved relative to the project root (no hardcoded absolutes).
"""

from __future__ import annotations

import csv
from pathlib import Path

ROOT = Path(__file__).resolve().parents[3]
INVENTORY = ROOT / "data" / "cleaned" / "corpus_inventory.csv"
TIER_B = ROOT / "data" / "cleaned" / "tier_b_sample_ids.csv"
OUT = ROOT / "supabase" / "seed.sql"


def sql_str(value: str | None) -> str:
    """Quote a SQL string literal, or NULL for empty/None."""
    if value is None or value == "":
        return "NULL"
    return "'" + value.replace("'", "''") + "'"


def sql_int(value: str | None) -> str:
    if value is None or value == "":
        return "NULL"
    return str(int(value))


def sql_bool(value: str) -> str:
    return "true" if str(value).strip().lower() in {"true", "1", "yes"} else "false"


def main() -> None:
    tier_b_ids = {
        row["programme_id"] for row in csv.DictReader(TIER_B.open(encoding="utf-8"))
    }

    with INVENTORY.open(encoding="utf-8") as f:
        programmes = list(csv.DictReader(f))

    lines: list[str] = []
    lines.append("-- ============================================================")
    lines.append("-- supabase/seed.sql — GENERATED by scripts/python/db/generate_seed.py")
    lines.append("-- Do not edit by hand; regenerate from data/cleaned/*.csv.")
    lines.append("-- Runs on `supabase db reset`. Idempotent (ON CONFLICT upsert).")
    lines.append("-- ============================================================")
    lines.append("")

    # ---- Coders (placeholders; link auth_user_id after inviting users) -------
    lines.append("insert into coder (coder_id, display_name, role) values")
    lines.append("    (1, 'Coder 1 (lead)', 'lead'),")
    lines.append("    (2, 'Coder 2', 'coder')")
    lines.append("on conflict (coder_id) do nothing;")
    lines.append("")

    # ---- Programmes ----------------------------------------------------------
    cols = (
        "programme_id, codigo_ruct, university_name, sector, ccaa, modality, "
        "degree, centro, sources, sources_count, ruct_anchored, fallback_flag, in_tier_b"
    )
    lines.append(f"insert into programme ({cols}) values")

    rows_sql: list[str] = []
    for r in programmes:
        in_tier_b = "true" if r["programme_id"] in tier_b_ids else "false"
        rows_sql.append(
            "    ("
            + ", ".join(
                [
                    sql_str(r["programme_id"]),
                    sql_str(r["codigo_ruct"]),
                    sql_str(r["university_name"]),
                    sql_str(r["sector"]),
                    sql_str(r["ccaa"]),
                    sql_str(r["modality"]),
                    sql_str(r["degree"]),
                    sql_str(r["centro"]),
                    sql_str(r["sources"]),
                    sql_int(r["sources_count"]),
                    sql_bool(r["ruct_anchored"]),
                    sql_str(r["fallback_flag"]),
                    in_tier_b,
                ]
            )
            + ")"
        )
    lines.append(",\n".join(rows_sql))
    lines.append("on conflict (programme_id) do update set")
    lines.append("    codigo_ruct     = excluded.codigo_ruct,")
    lines.append("    university_name = excluded.university_name,")
    lines.append("    sector          = excluded.sector,")
    lines.append("    ccaa            = excluded.ccaa,")
    lines.append("    modality        = excluded.modality,")
    lines.append("    degree          = excluded.degree,")
    lines.append("    centro          = excluded.centro,")
    lines.append("    sources         = excluded.sources,")
    lines.append("    sources_count   = excluded.sources_count,")
    lines.append("    ruct_anchored   = excluded.ruct_anchored,")
    lines.append("    fallback_flag   = excluded.fallback_flag,")
    lines.append("    in_tier_b       = excluded.in_tier_b;")
    lines.append("")

    OUT.write_text("\n".join(lines), encoding="utf-8")
    n_tier_b = sum(1 for r in programmes if r["programme_id"] in tier_b_ids)
    print(f"Wrote {OUT.relative_to(ROOT)}: {len(programmes)} programmes, {n_tier_b} in Tier B.")


if __name__ == "__main__":
    main()
